name: appointment_project_siprok
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  dio: ^4.0.3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.1.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.1.10
  google_maps_flutter_web: ^0.4.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
